name: Ubuntu GUI With Tailscale VNC

on:
  workflow_dispatch:

jobs:
  gui-tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Install XFCE Desktop, VNC server, and Tailscale
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies x11vnc xvfb wget curl unzip
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Set up VNC password
        run: |
          mkdir -p ~/.vnc
          x11vnc -storepasswd 'password123' ~/.vnc/passwd

      - name: Authenticate Tailscale
        run: |
          tailscale up --authkey=${{ secrets.NGROK_AUTHTOKEN }} --hostname=github-action-runner --accept-routes --advertise-tags=tag:github-action || tailscale up --force-reauth
          tailscale status

      - name: Start Virtual Desktop (Xvfb) and XFCE
        run: |
          nohup Xvfb :1 -screen 0 1024x768x16 &
          export DISPLAY=:1
          nohup startxfce4 &
          sleep 15

      - name: Start VNC server
        run: |
          export DISPLAY=:1
          nohup x11vnc -display :1 -rfbauth ~/.vnc/passwd -forever -shared -bg -nopw -listen 0.0.0.0 &

      - name: Show Tailscale IP address for VNC
        run: |
          echo "Tailscale private IPv4 for this runner:"
          tailscale ip -4
          echo "Connect VNC to this IP:5900 (password: password123) from a device in your Tailscale network."
